version: '3.4'

services:

  server:
    image: auth-service
    container_name: "auth-service"
    build: ./
    command: ./cmd/main
    ports:
      - 3000:3333
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=auth_service
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null