version: '3.4'

services:

  auth-service:
    image: auth-service
    container_name: "auth-service"
    build: ./
    command: /auth-service
    ports:
      - 3303:3303
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.7
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=auth_service
    volumes:
      - ./.data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null